services:
  redis:
    image: redis:8.0
    ports:
      - "6380:6379"
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DOCKER_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
      POSTGRES_DB: ${DOCKER_DATABASE_NAME}
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
